### ISSUE TITLE
En-tête X-LPL : tables arc-en-ciel & SHA-1

### ISSUE THREAD

**Issue by Berbe** [NextINpact/LaPresseLibreSDK#1]
Il est prévu que l'en-tête X-LPL contienne les informations X-PART & X-TS en complément d'un secret.

Un attaquant connait donc 2 des 3 ingrédients de la source du hash est sait que le nonce restant ne varie pas d'une requête à l'autre de et vers un même partenaire.
Cela est donc attaquable de multiples manières, par exemple par des tables arc-en-ciel, sur une collecte suffisante de requêtes/réponses entre LPL et un partenaire.

L'attaque est de plus facilité par l'usage de la fonction de hachage SHA-1 qui ne doit plus être considérée comme cryptographique car son inversion a été prouvée possible, la complexité de celle-ci ayant même été réduite.
Quand même le NIST, pourtant navigant en eaux grises (Dual_EC_DRBG, ECC Suite B), recommande le passage à la famille de suites SHA-2 et l'abandon complet de SHA-1 depuis 2010 (6 ans !), c'est que la suite sent très fort.

En bref :
1. X-LPL devrait reposer sur un élément aléatoire joint aux en-têtes (et non sur un horodatage certes mouvant mais prévisible, issu d'une série continue, et de complexité très faible)
2. X-LPL devrait utiliser une fonction de hachage cryptographique pour réduire de manière satisfaisante sa susceptibilité à une attaque

**Comment by pehadavid** [comment]
Bonjour,

Merci pour le rapport complet. @ryuKKu-  ?

**Comment by ryuKKu-** [comment]
Bonjour @Berbe , merci de ton retour.

Effectivement, une attaque par **rainbow tables** est envisageable sur le header **X-LPL** dans l'état actuel des choses. Cependant, ces headers permettent juste d'identifier si la plateforme avec laquelle La Presse Libre communique est un partenaire connu du service. Comme décrit dans le [wiki](https://github.com/NextINpact/LaPresseLibreSDK/wiki/Fonctionnement-des-web-services), la communication s'effectue via HTTPS, et le corps de la requête envoyée est chiffrée par **AES** avec un code différent du code secret utilisé pour hasher le header X-LPL. Il semble donc assez difficile pour un attaquant de passer à travers tous ces chiffrements pour récupérer les données voulues. 

Quant au choix du hashage SHA1, il est certes contestable, mais c'était avant tout pour des questions de performances. Je prend quand même en considérations tes remarques, et j'envisagerai peut être de passer de SHA1 à SHA256 ou SHA512 dans une future version du SDK. 

Si tu as d'autres remarques n'hésite pas.
