### ISSUE TITLE
Usage de mcrypt

### ISSUE THREAD

**Issue by FlorentATo** [NextINpact/LaPresseLibreSDK#3]
Le développement de l'extension mcrypt est à l'abandon depuis [bientôt 10ans](https://sourceforge.net/projects/mcrypt/files/Libmcrypt/) et son abandon progressif est en cours de discussions au sein de la communauté ([lien (2015-02)](https://wiki.php.net/rfc/removal_of_dead_sapis_and_exts), [lien (2016-01)](https://wiki.php.net/rfc/mcrypt-viking-funeral)).

Parmi les alternatives existantes, l'usage de [libsodium](https://github.com/jedisct1/libsodium) (basée sur [NaCl](https://nacl.cr.yp.to/)) est aujourd'hui [recommandé](https://paragonie.com/blog/2015/09/how-to-safely-implement-cryptography-in-any-application).

A défaut d'utiliser libsodium (qui reste la meilleure solution), vous pouvez vous replier sur [OpenSSL](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong).

A lire:
- http://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt
- https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly
- https://paragonie.com/blog/2015/11/choosing-right-cryptography-library-for-your-php-project-guide

**Comment by pehadavid** [comment]
merci pour la remarque, @ryuKKu- ?

**Comment by FlorentATo** [comment]
Fermeture sans commentaire ? Idem sur les 2 autres tickets. Pas terrible.
