### ISSUE TITLE
Prérequis PHP 5.2.X

### ISSUE THREAD

**Issue by FlorentATo** [NextINpact/LaPresseLibreSDK#5]
Toute version de PHP inférieur à 5.6 est considéré comme [end of life](https://secure.php.net/supported-versions.php).
Les dernières [statistiques](https://seld.be/notes/php-versions-stats-2016-1-edition) indiquent d'une part que PHP5.6 est majoritaire mais aussi que la popularité de PHP7 grimpe sans cesse.

Utiliser une version de PHP vielle de [10ans](http://www.php.net/ChangeLog-5.php#5.2.0) et officiellement déprécié n'est pas recommandable. Comme le reste de la communauté, je recommanderais PHP >= 5.6 min (ou mieux PHP 7).

**Comment by pehadavid** [comment]
Noté, merci pour la remarque. Cependant on offre juste un support pour cette version, nous n'avons rien de bloquant qui nous empêche de le proposer. Cependant, si un jour on se retrouve coincé, on hésitera pas à forcer les choses pour relever le prérequis.

**Comment by FlorentATo** [comment]
Alors n'attendez pas d'être coincé pour redéfinir vos prérequis. Go 5.6 ou au-dessus :)
