### ISSUE TITLE
Vecteur d'initialisation

### ISSUE THREAD

**Issue by FlorentATo** [NextINpact/LaPresseLibreSDK#6]
Le vecteur d'initialisation définit dans le fichier Config.php devrait être aléatoire et unique à chaque initialisation du cipher. Son unicité et son entropie doivent être **garanties** par l'usage d'un CSPRNG.

Selon moi, sa place n'est pas dans un fichier de configuration mais dans la construction de la fonction "GenerateUrl()".

Si vous décidez de supporter PHP 7, utilisez [random_bytes](https://secure.php.net/manual/en/function.random-bytes.php).
Dans le cas contraire, il existe une implémentation fiable de cette fonction pour PHP 5: https://github.com/paragonie/random_compat

**Comment by pehadavid** [comment]
Salut,

Les parties prenantes de la conversation chiffrée doivent pouvoir communiquer entre elles et par conséquent utiliser des paramètres similaires. On pourrait cependant  distribuer une deuxième passkey à chaque appel, qui une fois dérivée, pourrait donner un IV personnalisé. Je note pour amélioration.

**Comment by FlorentATo** [comment]
Hello,

par principe, le chiffrement symétrique s'effectue par l'usage d'une même **clé** uniquement.
Le vecteur d'initialisation (qui, par nature doit être aléatoire) permet à partir d'une même source d'obtenir deux ciphertext différents entre deux parties utilisant la même clé.

La bonne construction de l'IV est primordiale dans le processus de chiffrement.

Par ailleurs, la longueur de l'IV est généralement égale à la taille de bloc du cipher.
Ce qui n'est pas le cas ici: IV = 128 bit. Taille de bloc = 256 bit

**Comment by pehadavid** [comment]
Avec AES, la taille d'un bloc est de 128 bits, quelque soit la taille de la clé ;).
Ceci dit, je suis d'accord sur le fait q'un IV random apporte une sécurité supplémentaire et comme dit précédemment, on note pour amélioration sur une itération ultérieure des webservices.

**Comment by FlorentATo** [comment]
Effectivement j'ai écrit trop vite, l'IV est bien de même taille avec la taille de bloc.
Par contre, je réitère sur le fait que celui-ci doit impérativement être unique/message et cryptographiquement aléatoire ([lien](http://crypto.stackexchange.com/a/5191/37233), [lien](https://security.stackexchange.com/questions/15740/what-are-the-variables-of-aes)) donc construction à l'appel de GenerateUrl().
