### ISSUE TITLE
Mot de passe en clair ?

### ISSUE THREAD

**Issue by FlorentATo** [NextINpact/LaPresseLibreSDK#7]
Le wiki mentionne que le mot de passe de l'utilisateur fait partie des informations est envoyé aux partenaires. Nul part est précisé la méthode de hachage, cela signifie-t-il qu'il en clair dans la chaîne JSON (qui est certes "chiffrée") ?

Je n'apprendrai rien à personne en disant que cette approche est à proscrire absolument.

Dans la mesure où vous concevez une nouvelle plateforme de zéro, il serait opportun de se conformer aux bonnes pratiques dans le domaine de la sécurité et inciter vos partenaires à en faire de même.

Ainsi, si vous et vos partenaires visez PHP >= 5.5, vous pouvez utiliser les fonctions [password_hash()](https://secure.php.net/manual/en/function.password-hash.php) et [password_verify()](https://secure.php.net/manual/en/function.password-verify.php) pour le hashage de vos mots de passe.

Dans ce cas, il faut spécifier dans vos prérequis:
- l'algorithme ("PASSWORD_BCRYPT")
- nombre de rounds (~12)
- expliciter la non gestion du salt.

A lire:
- https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016

**Comment by pehadavid** [comment]
Salut ,

Je pense que tu fais référence notamment référence au Webservice de création de compte.
Le mot de passe ne transite **jamais** en clair. 

Chaque partenaire se voit remettre un passkey AES qui permet de chiffrer / déchiffrer les corps des chaque requête. De plus, chaque appel passe par un tunnel SSL ce qui rends au final l'opération suffisamment complexe et permet d'obtenir une sécurité maximale.Par exemple, en cas de faille SSL, la couche AES ajoute une seconde couche reconnue comme sûre.

Au final, la stratégie de stockage des mots de passe  appartient à chacun, et il ne fait aucun doute qu'aucun de nos partenaire ne s'amuse de stocker les mots de passe utilisateurs en clair ;)

Si tu as d'autres remarques / questions, n'hésite pas.

**Comment by FlorentATo** [comment]
Hello Pierre-Alain,

D'après le snippet ci-dessous:

`{\"Mail\":\"jean.dupont@gmail.com\",\"Password\":\"XXXXXXXXXXXXX\",\"CodeUtilisateur\":\"XXXXXXXXXX\"}`

Sous quelle forme est la chaîne de caractère "Password" ?

S'il s'agit de la séquence telle que saisie par l'utilisateur à la création du compte, vous êtes vulnérable à l'injection de code (" est l'exemple le plus évident).

Si la chaîne subit une forme assainissement et/ou transformation, quelle est-elle ?

Le paramétrage HTTPS conforme aux recommandations (TLS1.2, clé RSA/ECDSA de longueur suffisante, usage exclusif de ciphers AEAD, headers HSTS, etc.) ne fait qu'assurer le transit de l'information. Que ce passe-t-il si l'un des serveurs (le votre ou celui de votre partenaire) est compromis ?

A mon avis, la politique de gestion des mots de passe devrait être clarifiée dans le wiki. L'avènement de LPL devrait être une opportunité de rappeler les bonnes pratiques à toutes les partie prenantes :)

**Comment by pehadavid** [comment]
L'injection de mot de passe n'est pas possible pour la simple est bonne raison que nous vérifions (il existe quelques restrictions à la création du mot de passe, mais rien qui diminue drastiquement la nombre de caractères possibles) et que nous respectons l'échappement des caractères (encodage JSON, comme précisé dans la doc).

Pour revenir sur la sécurité de l'échange :
- Nous communiquons à travers HTTPS en suivant les recommandations actuelles (confidentialité de l'échange),
- Chaque appel est signé via un header spécifique, généré via un hash de données confidentielles (identification sûre des parties prenantes)
- Chaque corps de requête est  à son tour chiffré via AES  à l'aide d'une clé confidentielle. (sécurité applicative)

Pour un attaquant extérieur, il est (avec les moyens disponibles à ce jour) impossible d'effectuer une requête sur les webservices partenaire et/ou d'en écouter les entrées/sorties sans avoir ces 3 "clés" et c'est ce qui nous intéresse étant donné que c'est le service que nous proposons. 

Pour un attaquant ayant accès à la totalité des informations (accès complet aux données confidentielles et donc à l'infra partenaire), c'est un scénario sur lequel on est attentif, mais sur lequel il n'existe pas de solutions miracles. Si l'attaquant dispose d'un accès en écriture sur la couche applicative, il peut très bien patcher pour intercepter les mots de passes d'utilisateurs. Mais ce n'est pas propre à LPL, disons que c'est une question de sécurité plus globale pour le coup :)

Pour finir, nous n'offrons qu'un bridge et que chacun est responsable des données dans son S.I.
Nous travaillons en étroite collaboration avec les partenaires pour s'assurer que tout est conforme.

**Comment by FlorentATo** [comment]
Effectivement sur le papier vous jouez ceinture/bretelles considérant la nature des informations échangées. Je recommanderai tout de même de faire audité votre implémentation (sur les 3 points que tu énonces) par un professionnel de la sécurité/crypto.

Merci pour ces retours P-A.

**Comment by KanorUbu** [comment]
Bonjour
Je me demande si la meilleur solution se serait de mettre en place une identification par Oauth ?

**Comment by davlgd** [comment]
C'est l'une des pistes d'évolution envisagée, mais cela n'était pas un modèle bien accepté par une majorité d'éditeurs dans un premier temps et cela nécessitait une infrastructure relativement différente, sans forcément simplifier certains aspects. Du coup on a misé sur le modèle actuel, avec une possibilité d'offrir de l'OAuth éventuellement en phase 2 aux sites qui voudront le mettre en place.

Mais dans tous les cas, ça ne change rien à l'intérêt de proposer un compte créé directement chez le partenaire, qui peut fonctionner sans LPL au quotidien. 

Comme indiqué par PA, on s'est assuré que la sécurité était d'un niveau largement suffisant pour écarter tout problème, bien qu'il faille toujours être vigilant. L'utilisateur a ensuite la possibilité de changer son mot de passe s'il veut rajouter une couche de sécurité "par site". Mais d'un point de vue utilisateur, le plus gros souci concernant les mots de passe (hors de LPL), c'est le plus souvent que son login se fait en clair....
